#!/bin/sh
#
#  Copyright (C) 2005 Free Software Foundation, Inc.
#
#  Written by:	Adam Fedor <fedor@gnu.org>
#
#  This package is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public
#  License along with this package; if not, write to the Free
#  Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111 USA
#
#--------------------------------------------------------------------
#
# This is a simple script used to check the basic operation of an
# already installed GNUstep system. Assumes that the InstallGNUstep
# script was already run successfully
#
# To run this script, at the command line, type
#
# ./CheckGNUstep

#--------------------------------------------------------------------
# Check the shell. Do a few checks on how the shell behaves, so that we
# can run and display things properly.
#--------------------------------------------------------------------
case `echo "testing\c"; echo 1,2,3`,`echo -n testing; echo 1,2,3` in
  *c*,-n*) ECHO_N= ECHO_C='
' ECHO_T='      ' ;;
  *c*,*  ) ECHO_N=-n ECHO_C= ECHO_T= ;;
  *)       ECHO_N= ECHO_C='\c' ECHO_T= ;;
esac


#--------------------------------------------------------------------
# Check command line arguments
#--------------------------------------------------------------------
RUNDIR=`pwd`
SRCDIR=`dirname $0`
# Find absolute path to SRCDIR
SRCDIR=`cd $SRCDIR && pwd`

gs_command_line=${@}
gs_run_batch=no
gs_system_prefix=
BUILDDIR=.
while test $# != 0
do
  gs_option=
  case $1 in
    --help | -h)
      echo "$0: Script to install GNUstep core libraries"
      echo "Options:"
      echo "  --help	- Print help"
      echo "  --batch	- Don't ask any questions"
      echo
      echo "  --prefix={dir}	- GNUstep system root location"
      echo "  --builddir={dir}	- Location to put log files of results"
      exit 0
      ;;
    --batch | -b)
      gs_run_batch=yes;;
    --*=*)
      gs_option=`expr "x$1" : 'x\([^=]*\)='`
      gs_optarg=`expr "x$1" : 'x[^=]*=\(.*\)'`
      ;;
    *)
      ;;
  esac

  case $gs_option in
    --prefix)
      gs_system_prefix=$gs_optarg;; 
    --builddir)
      BUILDDIR=$gs_optarg;;
    *)
      ;;
  esac
  shift
done

#--------------------------------------------------------------------
# Misc setup. Make sure we know where everything is
#--------------------------------------------------------------------

GDNC_IN_PATH=no
which gdnc > /dev/null
if [ $? = 0 ]; then
  GDNC_IN_PATH=yes
fi
if [ x$GNUSTEP_SYSTEM_ROOT = x -a $GDNC_IN_PATH = no ]; then
  echo GNUSTEP_SYSTEM_ROOT not set. Make sure to source the GNUstep.sh
  echo or that you have put the GNUstep tools in your path.
fi

. scripts/programs.sh

#--------------------------------------------------------------------
# Check build directory.
#--------------------------------------------------------------------
cd $BUILDDIR
if [ \! -d logs ]; then
  mkdir logs
fi
gs_write_output=yes
if [ \! -d logs ]; then
  echo "************************************************************"
  echo "Cannot create the logs. No results will be written to a file"
  gs_write_output=no
fi

if test $gs_write_output = yes; then
  exec 5>logs/checkgnustep.log
  GSPROGRAMLOG=logs/check_program.log
else
  exec 5>/dev/null
  GSPROGRAMLOG=/dev/null
fi
echo "Check log for the GNUstep" >&5
echo >&5
echo "Arguments: $gs_command_line" >&5
echo "System Root: $GNUSTEP_SYSTEM_ROOT" >&5
echo >&5
echo "Checking GNUstep (This script is not complete yet):"

#--------------------------------------------------------------------
# Check ps
#--------------------------------------------------------------------
echo "Checking computer setup:"
echo "Checking computer setup:" >&5
gs_find_ps

#--------------------------------------------------------------------
# Check daemons
#--------------------------------------------------------------------
echo "Checking GNUstep daemons:"
echo "Checking GNUstep daemons:" >&5
GSARGS=
GSPROGRAM=gdomap
gs_check_program
gs_gdomap=$gs_exit_status

# FIXME: Should really search for this per-user
GSPROGRAM=gdnc
gs_check_program
gs_gdnc=$gs_exit_status

# FIXME: Check that we have a window server before doing this
GSPROGRAM=gpbs
#gs_check_program
#gs_gpbs=$gs_exit_status

if [ $gs_gdomap != 0 -o $gs_gdnc != 0 ]; then
  gs_check_error
  exit 1
fi

#--------------------------------------------------------------------
# Check Tools
#--------------------------------------------------------------------
echo "Checking GNUstep tools:"
echo "Checking GNUstep tools:" >&5
GSARGS="read NSGlobalDomain"
GSPROGRAM=defaults
gs_check_program

if [ $gs_exit_status != 0 ]; then
  gs_check_error
  exit 1
fi



