#!/bin/sh
#
# @configure_input@
#

if [ ! -f setupvars ]; then
  echo "*********************************************************************"
  echo "There was a problem checking the configuration of you system."
  echo "One possible cause is that you do not have a C or Objective-C"
  echo "compiler on your system"
  echo "Please see the instructions that came with your operating system"
  echo "for installing the GNU GCC compiler and installing a developer"
  echo "system for compiling programs"
  echo "*********************************************************************"
  exit 1
fi
. setupvars

GOT_ERRORS=no

echo "*********************************************************************"
echo "* Startup configuration report                                      *" 
echo "*********************************************************************"
if test -n "$SETUP_ERRORS"; then
  #echo "The configure script found some warnings and/or errors"
  for errid in $SETUP_ERRORS
  do
    errid=`echo $errid | tr -d ' '`
    errors=`echo $errid | grep -c E`
    if test $errors = 1; then
      GOT_ERRORS=yes
    fi
    if test $errid = I999; then
      break;
    fi
    echo "--------------------------------------------------------------"
    if test $AWK = gawk; then
      $AWK -v errid=$errid -f ErrorList.awk ErrorList
    else
      $AWK -f ErrorList.awk errid=$errid ErrorList
    fi
  done
else
  echo "  No problems found during configuration"
fi
echo "*********************************************************************"
if test $GOT_ERRORS = yes; then
  echo "Please correct the above errors before installing GNUstep"
  exit 1
elif test $GNUSTEP_INSTALLED = no; then
  echo "You are ready to install GNUstep. However, please pay special"
  echo "attention to any warnings printed above and consider correcting"
  echo "them if they seem important"
else
  echo "Now continue with the GNUstep installation"
  echo "  gnustep-make installed: " $GNUSTEP_INSTALLED
  echo "  gnustep-base installed: " $GNUSTEP_BASE_INSTALLED
  echo "  gnustep-gui  installed: " $GNUSTEP_GUI_INSTALLED
  echo "  gnustep-back installed: " $GNUSTEP_BACK_INSTALLED
fi
