#!/bin/sh
#
# Test the compilation and installation of GNUstep. This script does:
#   1. Runs "svn update" on the GNUstep source files
#   2. Runs the startup/InstallGNUstep script
#   3. Runs the testsuite if available
#   4. Uploads the results to ftp.gnustep.org
#
# Here's how to check out a copy of the source from SVN for testing:
#   svn co http://svn.gna.org/svn/gnustep/autotest
#
# Then setup a crontab and/or batch file to run the script:
#   autotest/startup/scripts/test-gnustep
#
# NOTE: This script does not need to be run as root nor have any special
# privleges. Since the installation is in the user's home directory, 
# everything should work with normal privliges.
#
# Here's an example of a cron script I use to run this script every night
# on a solaris box:
#
# PATH=/usr/local/bin:/usr/ccs/bin:$PATH
# export PATH
# LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH
# cd $HOME/src/gstep/autotest/
# rm -f gnustep-testrun.txt
# $HOME/src/gstep/autotest/startup/scripts/test-gnustep > gnustep-testrun.txt 2>&1
#
# Additional documentation:
#   This script assumes it is being run from a source checkout of the
# gnustep directory strucuture (startup and core are required at the same 
# level).  It tries to find the GNUstep source files, by checking in the
# current directory, the directory ../.. from where the script was run
# from, or as a last resort:
#    $HOME/src/gnustep-'$hostname -s`
#
# The files are installed into 
#    $HOME/gnustep-'$hostname -s`
#
# However you can set the installation directory with a --prefix option
#
# To customize this script, you might have to change other things
#

gs_platform()
{
  gs_build=`$STARTUP/config.guess` 2>&1
  if test -z "$gs_build"; then
    gs_build=unknown
  else
    gs_build=`$STARTUP/config.sub $gs_build`
  fi
  if test -z "$gs_build"; then
    gs_build=unknown
  fi
  gs_build_cpu=`echo $gs_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
  gs_build_vendor=`echo $gs_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
  gs_build_os=`echo $gs_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
}

# Note: hostname -s doesn't work on every system...
if [ x"$NAME" = x ]; then
  NAME=`hostname | tr '.' ' ' | awk '{print $1}'`
fi

if [ -z "$MAKE" ]; then
  if gmake -v >/dev/null 2>&1
  then
    MAKE=gmake
  else
    MAKE=make
  fi
fi

# Figure out where the GNUstep files are
RUNDIR=`pwd`
SRCDIR=`dirname $0`
# Find absolute path to SRCDIR
SRCDIR=`cd $SRCDIR && pwd`
if [ -f InstallGNUstep ]; then
  TOPDIR=`cd ..; pwd`
elif [ -f startup/InstallGNUstep ]; then
  TOPDIR=$RUNDIR
elif [ -f $SRCDIR/../InstallGNUstep ]; then
  TOPDIR=$SRCDIR/../..
elif [ -f Startup/InstallGNUstep ]; then
  TOPDIR=$RUNDIR
else
  TOPDIR=$HOME/src/gnustep-$NAME
fi
# Where is core?
BUILDDIR=$TOPDIR/core
if [ -d $TOPDIR/modules/core ]; then
  BUILDDIR=$TOPDIR/modules/core
fi
# Where is the testsuite
TESTDIR=
if [ -d $TOPDIR/testsuite ]; then
  TESTDIR=$TOPDIR/testsuite
elif [ -d $TOPDIR/tests/testsuite ]; then
  TESTDIR=$TOPDIR/tests/testsuite
elif [ -d $TOPDIR/modules/tests/testsuite ]; then
  TESTDIR=$TOPDIR/modules/tests/testsuite
fi
# Name of startup
cd $TOPDIR
STARTUP=$TOPDIR/startup
if [ -f Startup/InstallGNUstep ]; then
  STARTUP=$TOPDIR/Startup
fi

# OK, now start
if [ \! -f $STARTUP/InstallGNUstep ]; then
  echo "ERROR: Could not find GNUstep source directory"
  exit 1
fi
gs_platform
if [ x"$GS_CANONICAL" != x ]; then
  gs_build=$GS_CANONICAL
fi

gs_nocvs=no
gs_clean=no
gs_root_prefix=$HOME/gnustep-$NAME
while test $# != 0
do
  case $1 in
    --help | -h)
      echo "$0: Script to test GNUstep core libraries"
      echo "Options:"
      echo "  --help	- Print help"
      echo "  --nocvs	- don't update from cvs"
      exit 0
      ;;
    --nocvs | -n)
      gs_nocvs=yes;;
    --clean | -c)
      gs_clean=yes;;
    --*=*)
      gs_option=`expr "x$1" : 'x\([^=]*\)='`
      gs_optarg=`expr "x$1" : 'x[^=]*=\(.*\)'`
      ;;
    *)
      ;;
  esac

  case $gs_option in
    --prefix)
      gs_root_prefix=$gs_optarg;;
    *)
      ;;
  esac
  shift
done

# Update source
if [ "$gs_nocvs" != yes ]; then
  cd $BUILDDIR; svn update; cd ..
  cd $STARTUP; svn update; cd ..
  cd $TESTDIR; svn update; cd ..
fi

# Remove the old files
rm -rf $gs_root_prefix

# Run the install
GNUSTEP_CONFIG_FILE=$gs_root_prefix/GNUstep.conf
export GNUSTEP_CONFIG_FILE
cd $STARTUP
./InstallGNUstep --batch --prefix=$gs_root_prefix --nopriv
gsexitstatus=$?

# Run the testsuite
if [ $gsexitstatus = 0  -a -n "$TESTDIR" ]; then
  if [ x$LIBRARY_COMBO = xapple-apple-apple ]; then
    . $gs_root_prefix/Library/GNUstep/Makefiles/GNUstep.sh
  else
    . $gs_root_prefix/System/Library/Makefiles/GNUstep.sh
  fi
  cd $TESTDIR
  echo
  echo "--------------------------------------------------------------"
  echo Running Base Testsuite
  echo "--------------------------------------------------------------"
  rm -f testsuite.log tests.log tests.sum tests-base.sum
  $gs_root_prefix/System/Tools/gnustep-tests base | tee testsuite.log
  mv tests.sum tests-base.sum
  echo "--------------------------------------------------------------"
  echo Running Gui Testsuite
  echo "--------------------------------------------------------------"
  $gs_root_prefix/System/Tools/gnustep-tests gui | tee -a testsuite.log
  rm -f $STARTUP/$NAME-$gs_build-testsuite.log
  cat tests-base.sum tests.sum > $STARTUP/$NAME-$gs_build-testsuite.log
fi

# Archive the results
echo "--- Archive Results ---"
cd $STARTUP
rm -f $NAME-$gs_build-results.txt
rm -f $NAME-$gs_build-logs.tar.gz
GSDATE=`date`
gs_success=no
if [ $gsexitstatus != 0 ]; then
  mv $BUILDDIR/logs.tar.gz $NAME-$gs_build-logs.tar.gz
  echo "$NAME Fail Compile $gs_build $GSDATE" > $NAME-$gs_build-results.txt
else
  echo "$NAME Success Compile $gs_build $GSDATE" > $NAME-$gs_build-results.txt
  gs_success=yes
fi

# Upload the results somewhere
echo "--- Upload Results ---"
echo "NOTE: Ignore any errors about missing files below"
ftp -n ftp.gnustep.org << EOF
user anonymous bug-gnustep@gnu.org
cd pub/incoming
put $NAME-$gs_build-results.txt
binary
put $NAME-$gs_build-logs.tar.gz
put $NAME-$gs_build-testsuite.log
bye
EOF

DIRS="make base gui back"
if [ $gs_clean = yes -a -d $gs_root_prefix ]; then
  echo "--- Cleaning Up ---"
  if [ x$LIBRARY_COMBO = xapple-apple-apple ]; then
    . $gs_root_prefix/Library/GNUstep/Makefiles/GNUstep.sh
  else
    . $gs_root_prefix/System/Library/Makefiles/GNUstep.sh
  fi
  cd $BUILDDIR
  for d in $DIRS; do
    cd $d; make distclean; cd ..
  done
  rm -rf $gs_root_prefix
fi
